### PR TITLE
feat: replace pip with uv for 60% faster integration tests

### PR DESCRIPTION
**Pull request by anubhav756**
## Overview
This PR migrates our integration test pipelines from `pip` to `uv`, reducing installation time by ~60% and significantly improving dependency resolution stability.

## Changes
* Updated `integration.cloudbuild.yaml` for all packages (`toolbox-core`, `toolbox-adk`, `toolbox-langchain`, `toolbox-llamaindex`) to use `uv` and persistent virtual environments.
* Upgraded `typing-extensions>=4.12.2` in `toolbox-adk` to resolve a conflict masked by `pip` but caught by `uv`'s stricter resolver.

> [!NOTE]
> This PR does not only speeds up CI but also provides the resolution capabilities needed for upcoming Python 3.14 support (https://github.com/googleapis/mcp-toolbox-sdk-python/pull/494).
>
> ### Problem
> There were 2 problems that occur with adding Python 3.14 without `uv`:
> 1. The resolver hangs for 20+ minutes printing warnings like:
> ```
> INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints...
> INFO: pip is looking at multiple versions of pydantic-core to determine which version is compatible...
> ```
> 2. In its desperation to find any working combination, `pip` eventually backtracks to ancient versions of libraries. These older versions contain C-extensions that are fundamentally incompatible with the Python 3.14 C API, causing build failures:
> ```
> error: implicit declaration of function ‘PyUnicode_New’
> error: ‘PyUnicode_KIND’ undeclared
> ```
>
> ### Solution
> `uv`'s resolver is significantly faster and correctly navigates the dependency graph without excessive backtracking, essentially forcing the resolver to pick newer, compatible source distributions instead of falling back to broken legacy versions. This prevents the build from hanging and ensures we install versions of `pydantic-core` (2.41+) that actually compile on Python 3.14.

### CODE REVIEW

File: packages/toolbox-adk/integration.cloudbuild.yaml [hunk 1]
```diff
@@ -16,20 +16,26 @@ steps:
...
+    env:
     args:
-      - install
-      - '-e'
-      - 'packages/toolbox-adk[test]'
-      - '--user'
-    entrypoint: pip
+      - '-c'
+      - |
+        pip install uv
```
Comment (averikitsch) [inline packages/toolbox-adk/integration.cloudbuild.yaml]: do we need to install uv again or just reactive the venv?

Comment (anubhav756) [reply packages/toolbox-adk/integration.cloudbuild.yaml]: Great catch! Initially, I had to re-install `uv` in every step because Cloud Build runs each step in a fresh, ephemeral container—so while the `/workspace` volume persists, the system binaries (`/usr/local/bin/uv`) get wiped.

However, your question made me give it a second thought. I've updated the config to install `uv` directly inside the persistent venv (`/workspace/venv`) during the first step.

Now, `uv` persists automatically alongside our dependencies, so now we only need `pip install uv` once. Much cleaner!

Thanks for the idea! 🙂

**Review by averikitsch — APPROVED** [review]
